server:
  port: 8888

spring:
  application:
    name: config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          # Repositório de configuração centralizada (arquivos em src/main/resources/config)
          search-locations: classpath:/config
